[package]
name = "gitrack"
version = "0.1.0"
edition = "2021"
authors = ["containerscrew info@containerscrew.com"]
repository = "https://github.com/containerscrew/gitrack"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
colored = "2.1.0"
git2 = "0.19.0"
walkdir = "2.5.0"
home = "0.5.9"