name: Build 🪛

on:
  pull_request:
  push:
    paths:
      - 'src/**'
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/build.yml
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu

          - os: macOS-latest
            target: x86_64-apple-darwin

          - os: macOS-latest
            target: aarch64-apple-darwin
            
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Setup dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install musl-dev musl-tools pkg-config make
  
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true
      
      - name: Run the binary
        
        run: ./target/${{ matrix.target }}/release/gitrack -p /tmp