name: Release 📦

permissions:
  contents: write
  pull-requests: write

on:
  push:
#    tags:
#      - 'v*.*.*'

jobs:
  release:
    name: Multi-Arch Build
    strategy:
      matrix:
        platform:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-musl }
          - { os: ubuntu-latest, target: aarch64-unknown-linux-musl }
          - { os: macOS-latest, target: x86_64-apple-darwin }
          - { os: macOS-latest, target: aarch64-apple-darwin }
#          - { os: windows-latest, target: x86_64-pc-windows-msvc }
#          - { os: windows-latest, target: aarch64-pc-windows-msvc }
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies for musl
        if: matrix.platform.os == 'ubuntu-latest'
        run: sudo apt-get -qq install musl-tools

      - name: Install Rust toolchain
        run: rustup target add ${{ matrix.platform.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.platform.target }}

#      - name: Set container tag
#        id: set_tag
#        run: |
#          # Extract the tag name from the full reference
#          IMAGE_TAG=$(echo "${{ github.ref }}" | sed 's|.*/||')
#          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"
#
#      - name: Package zip
#        run: |
#          make package ARCH=${{ matrix.platform.release_for }} TARGET=${{ matrix.platform.target }} TAG=${{ env.IMAGE_TAG }}
#
#      - name: Release
#        uses: softprops/action-gh-release@v2
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          files: |
#            CHANGELOG.md
#            LICENSE
#        env:
#          token: ${{ secrets.RELEASE_TOKEN }}
#          generate_release_notes: true
#          append_body: true
#          draft: true #for testing
