name: Test 🤖

on:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  test_fmt_lint:
    name: Test, Fmt & Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add rustfmt clippy
      # Test
      - name: Run cargo test
        run: cargo test --all-features

      # Format
      - name: Check formatting
        run: cargo fmt --all -- --check

      # Lint
      - name: Run clippy
        run: cargo clippy --all-features -- -D warnings
